### ISSUE TITLE
Pb connection avec le décodeur Livebox

### ISSUE THREAD

**Issue by ramet** [Aymkdn/assistant-livebox#8]
Le plugin fonctionnait bien début novembre, l'IP du décodeur est statique et n'a pas changée, mais j'obtiens maintenant l'erreur suivante. Une mise à jour Orange ? 

```
[assistant] (2020-12-02 18:23:42) Commande reçue:  [ 'livebox_on' ]
[assistant] (2020-12-02 18:23:42) Appel du plugin 'livebox'
[assistant] (2020-12-02 18:24:45) Commande reçue:  [ 'livebox_off' ]
[assistant] (2020-12-02 18:24:45) Appel du plugin 'livebox'
[assistant-livebox] Erreur : RequestError: Error: connect ETIMEDOUT 192.168.1.16:8080
    at new RequestError (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/ramet/Work/assistant-plugins/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.onRequestError (/Users/ramet/Work/assistant-plugins/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:376:20)
    at Socket.socketErrorListener (node:_http_client:490:9)
    at Socket.emit (node:events:376:20)
    at emitErrorNT (node:internal/streams/destroy:188:8) {
  cause: Error: connect ETIMEDOUT 192.168.1.16:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.16',
    port: 8080
  },
  error: Error: connect ETIMEDOUT 192.168.1.16:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.16',
    port: 8080
  },
  options: {
    url: 'http://192.168.1.16:8080/remoteControl/cmd?operation=10',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^
RequestError: Error: connect ETIMEDOUT 192.168.1.16:8080
    at new RequestError (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/ramet/Work/assistant-plugins/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/ramet/Work/assistant-plugins/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.onRequestError (/Users/ramet/Work/assistant-plugins/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:376:20)
    at Socket.socketErrorListener (node:_http_client:490:9)
    at Socket.emit (node:events:376:20)
    at emitErrorNT (node:internal/streams/destroy:188:8) {
  cause: Error: connect ETIMEDOUT 192.168.1.16:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.16',
    port: 8080
  },
  error: Error: connect ETIMEDOUT 192.168.1.16:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.16',
    port: 8080
  },
  options: {
    url: 'http://192.168.1.16:8080/remoteControl/cmd?operation=10',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
```

**Comment by Aymkdn** [comment]
Aucune idée… Je ne possède pas de Livebox donc je ne pourrai pas aider… Le port 8080 a l'air d'être fermé…

As-tu essayé de redémarrer ta Livebox ? Des fois que…
Sinon, essaie de la scanner pour voir les ports ouverts.

Hormis ça, je ne sais pas, désolé !

**Comment by Aymkdn** [comment]
Si tu trouves, je veux bien que tu partages, si d'autres ont ce soucis.

**Comment by ramet** [comment]
C'est encore une erreur de ma part. Pour une raison inconnue le décodeur s'est connecté en wifi plutôt que par le cable ethernet et s'est donc retrouvé avec une autre adresse IP. Tout fonctionne parfaitement. Je ferme donc cette issue.
