### ISSUE TITLE
assistant-livebox HS

### ISSUE THREAD

**Issue by spoof54** [Aymkdn/assistant-livebox#9]
Hello, 

Tout d'abord merci pour cet outil qui est génial pour piloter le décodeur depuis la Google Home !

Je rencontre depuis quelques jours un soucis.
Les commandes n'exécutent plus rien et dans les logs j'ai ceci :

```
[assistant] Connexion au flux de PushBullet...
[assistant] (2021-05-18 15:19:19) Connecté ! Prêt à exécuter les ordres.
[assistant] (2021-05-18 15:19:58) Commande reçue:  [ 'livebox_on,wait3000,zappe sur sur la 16' ]
[assistant] (2021-05-18 15:19:58) Appel du plugin 'livebox'
[assistant-livebox] Erreur : RequestError: Error: connect ETIMEDOUT 192.168.1.xx:8080
    at new RequestError (C:\assistant-plugins\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\assistant-plugins\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (C:\assistant-plugins\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8) {
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 192.168.1.xx:8080',
  cause: Error: connect ETIMEDOUT 192.168.1.xx:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.xx',
    port: 8080
  },
  error: Error: connect ETIMEDOUT 192.168.1.xx:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.1.xx',
    port: 8080
  },
  options: {
    url: 'http://192.168.1.xx:8080/remoteControl/cmd?operation=10',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
(node:3248) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 192.168.1.xx:8080
    at new RequestError (C:\assistant-plugins\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\assistant-plugins\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\assistant-plugins\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (C:\assistant-plugins\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
(node:3248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Mon décodeur a bien l'adresse 192.168.1.xx, vérifiée dans les équipements connectés sur l'interface Livebox.

C'est comme si le décodeur n'était plus joignable sur ce port...

Merci de ton aide !

Bonne journée.

Steven

**Comment by Aymkdn** [comment]
As-tu essayé de simplement redémarrer ton décodeur ?

**Comment by spoof54** [comment]
Autant pour moi, l'adresse IP diffusée par la Livebox concernant le décodeur était erronée...
Je l'ai affichée sur le décodeur directement et j'ai cette fois la bonne adresse ! 
Merci de ta rapidité en tout cas !
